function GeneratedWebsite({ websitePrompt }) {
  if (!websitePrompt) return null;

  const colors = {
    Blue: "#2563eb",
    Purple: "#7c3aed",
    Green: "#16a34a",
    Black: "#111827",
  };

  const primary = colors[websitePrompt.color] || "#2563eb";

  const background = websitePrompt.darkMode ? "#111827" : "#f8fafc";
  const text = websitePrompt.darkMode ? "white" : "#111827";

  return (
    <div
      style={{
        background,
        color: text,
        minHeight: "100vh",
        padding: "40px",
      }}
    >
      {/* Navbar */}

      <nav
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "50px",
        }}
      >
        <h2 style={{ color: primary }}>
          {websitePrompt.title}
        </h2>

        <button
          style={{
            background: primary,
            color: "white",
            border: "none",
            padding: "10px 20px",
            borderRadius: "8px",
          }}
        >
          Contact
        </button>
      </nav>

      {/* Hero */}

      <div
        style={{
          textAlign: "center",
          marginBottom: "70px",
        }}
      >
        <h1 style={{ fontSize: "50px" }}>
          {websitePrompt.heading}
        </h1>

        <p
          style={{
            fontSize: "20px",
            margin: "20px 0",
          }}
        >
          {websitePrompt.description}
        </p>

        <button
          style={{
            background: primary,
            color: "white",
            border: "none",
            padding: "15px 35px",
            borderRadius: "12px",
            fontSize: "18px",
          }}
        >
          {websitePrompt.button}
        </button>
      </div>

      {/* Template */}

      {websitePrompt.template === "Business" && (
        <div>
          <h2 style={{ color: primary }}>Our Services</h2>

          <div
            style={{
              display: "flex",
              gap: "20px",
              marginTop: "30px",
            }}
          >
            <div style={cardStyle}>
              <h3>Consulting</h3>
              <p>Grow your business with AI solutions.</p>
            </div>

            <div style={cardStyle}>
              <h3>Marketing</h3>
              <p>Reach more customers worldwide.</p>
            </div>

            <div style={cardStyle}>
              <h3>Support</h3>
              <p>24×7 professional support.</p>
            </div>
          </div>
        </div>
      )}

      {websitePrompt.template === "Restaurant" && (
        <div>
          <h2 style={{ color: primary }}>Popular Dishes</h2>

          <div
            style={{
              display: "flex",
              gap: "20px",
              marginTop: "30px",
            }}
          >
            <div style={cardStyle}>🍕 Pizza</div>
            <div style={cardStyle}>🍔 Burger</div>
            <div style={cardStyle}>🍝 Pasta</div>
          </div>
        </div>
      )}

      {websitePrompt.template === "Portfolio" && (
        <div>
          <h2 style={{ color: primary }}>Projects</h2>

          <div
            style={{
              display: "flex",
              gap: "20px",
              marginTop: "30px",
            }}
          >
            <div style={cardStyle}>AI Website Builder</div>
            <div style={cardStyle}>Hospital System</div>
            <div style={cardStyle}>E-Commerce App</div>
          </div>
        </div>
      )}

      <footer
        style={{
          textAlign: "left",
          marginTop: "80px",
          opacity: 0.7,
        }}
      >
        Generated by AI Website Builder
      </footer>
    </div>
  );
}

const cardStyle = {
  flex: 1,
  background: "white",
  color: "#111827",
  padding: "30px",
  borderRadius: "15px",
  textAlign: "center",
  boxShadow: "0 10px 20px rgba(0,0,0,.1)",
};

export default GeneratedWebsite;